"""Pydantic schema package."""

from app.schemas.alert import (
    AlertCheckResponse,
    AlertCreate,
    AlertDeleteResponse,
    AlertDetailResponse,
    AlertListResponse,
    AlertResponse,
    AlertUpdate,
)
from app.schemas.auth import (
    TokenData,
    TokenResponse,
    UserCreate,
    UserLogin,
    UserResponse,
)
from app.schemas.backtest import (
    BacktestRequest,
    BacktestResponse,
    BacktestResultResponse,
    EquityPointResponse,
    TradeResponse,
)
from app.schemas.common import MetaResponse
from app.schemas.portfolio import (
    HoldingDeleteResponse,
    PortfolioCreate,
    PortfolioDeleteResponse,
    PortfolioDetailResponse,
    PortfolioHoldingAdd,
    PortfolioHoldingResponse,
    PortfolioListResponse,
    PortfolioResponse,
)
from app.schemas.screener import (
    ScreenerCondition,
    ScreenerRequest,
    ScreenerResponse,
    ScreenerResultItem,
)
from app.schemas.stock import (
    IndicatorPointResponse,
    PricePointResponse,
    StockDetailResponse,
    StockHistoryResponse,
    StockIndicatorsResponse,
    StockListResponse,
    StockResponse,
    StockValuationResponse,
    ValuationResponse,
)
from app.schemas.watchlist import (
    WatchlistCreate,
    WatchlistDeleteResponse,
    WatchlistDetailResponse,
    WatchlistItemResponse,
    WatchlistListResponse,
    WatchlistResponse,
    WatchlistUpdate,
)

__all__ = [
    "TokenData",
    "TokenResponse",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "MetaResponse",
    "StockResponse",
    "PricePointResponse",
    "IndicatorPointResponse",
    "ValuationResponse",
    "StockListResponse",
    "StockDetailResponse",
    "StockHistoryResponse",
    "StockIndicatorsResponse",
    "StockValuationResponse",
    "WatchlistCreate",
    "WatchlistUpdate",
    "WatchlistItemResponse",
    "WatchlistResponse",
    "WatchlistListResponse",
    "WatchlistDetailResponse",
    "WatchlistDeleteResponse",
    "ScreenerCondition",
    "ScreenerRequest",
    "ScreenerResponse",
    "ScreenerResultItem",
    "BacktestRequest",
    "TradeResponse",
    "EquityPointResponse",
    "BacktestResultResponse",
    "BacktestResponse",
    "PortfolioCreate",
    "PortfolioHoldingAdd",
    "PortfolioHoldingResponse",
    "PortfolioResponse",
    "PortfolioListResponse",
    "PortfolioDetailResponse",
    "PortfolioDeleteResponse",
    "HoldingDeleteResponse",
    "AlertCreate",
    "AlertUpdate",
    "AlertResponse",
    "AlertListResponse",
    "AlertDetailResponse",
    "AlertDeleteResponse",
    "AlertCheckResponse",
]
